'use strict';

export default {
    LIST_FETCH_START: 'LIST_FETCH_START',
    LIST_FETCH_SUCCESS: 'LIST_FETCH_SUCCESS',
    LIST_FETCH_FAIL: 'LIST_FETCH_FAIL',

    ITEM_FETCH_START: 'ITEM_FETCH_START',
    ITEM_FETCH_SUCCESS: 'ITEM_FETCH_SUCCESS',
    ITEM_FETCH_FAIL: 'ITEM_FETCH_FAIL'
};
